GET http://localhost:3000/

### // GET - /posts - grazins visus postus
GET http://localhost:3000/posts

### // GET - /posts/dates - grazins visus postus
GET http://localhost:3000/posts/dates

### // GET - /posts id
GET http://localhost:3000/posts?id=4

### // Creat new POst
POST http://localhost:3000/posts
Content-Type: application/json

{
"title": "Post 18",
"content": "Body of post 8",
"date": "2023-11-01",
}