GET http://localhost:3000/

### // GET - /posts - grazins visus postus
GET http://localhost:3000/posts

### // GET - /posts/dates - grazins visus postus
GET http://localhost:3000/posts/dates

### // GET - /posts id
GET http://localhost:3000/posts/5

### // GET - /posts search
GET http://localhost:3000/posts/search?q=titi

### // Creat new POst
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Post 9",
  "content": "Body of post 8",
  "date": "2023-11-01"
}